// <auto-generated />
using System;

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

using OrganizerBlazorApp.Infrastructure.Data;

#nullable disable

namespace OrganizerBlazorApp.Infrastructure.Migrations
{
  [DbContext(typeof(AppDbContext))]
  [Migration("20260427114020_InitialCreate")]
  partial class InitialCreate
  {
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
      modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

      modelBuilder.Entity("OrganizerBlazorApp.Domain.Entities.Attachment", b =>
          {
            b.Property<Guid>("Id")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("TEXT");

            b.Property<DateTime>("CreatedAt")
                      .HasColumnType("TEXT");

            b.Property<string>("Extension")
                      .IsRequired()
                      .HasColumnType("TEXT");

            b.Property<string>("FileName")
                      .IsRequired()
                      .HasColumnType("TEXT");

            b.Property<string>("FilePath")
                      .IsRequired()
                      .HasColumnType("TEXT");

            b.Property<Guid>("ParentUnitId")
                      .HasColumnType("TEXT");

            b.Property<int>("Type")
                      .HasColumnType("INTEGER");

            b.Property<DateTime?>("UpdatedAt")
                      .HasColumnType("TEXT");

            b.HasKey("Id");

            b.HasIndex("ParentUnitId");

            b.ToTable("Attachments", (string)null);
          });

      modelBuilder.Entity("OrganizerBlazorApp.Domain.Entities.TodoUnit", b =>
          {
            b.Property<Guid>("Id")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("TEXT");

            b.Property<DateTime>("CreatedAt")
                      .HasColumnType("TEXT");

            b.Property<DateTime>("Deadline")
                      .HasColumnType("TEXT");

            b.Property<string>("Description")
                      .HasColumnType("TEXT");

            b.Property<bool>("IsRequired")
                      .HasColumnType("INTEGER");

            b.Property<Guid?>("ParentUnitId")
                      .HasColumnType("TEXT");

            b.Property<int>("Status")
                      .HasColumnType("INTEGER");

            b.Property<string>("Title")
                      .IsRequired()
                      .HasColumnType("TEXT");

            b.Property<DateTime?>("UpdatedAt")
                      .HasColumnType("TEXT");

            b.HasKey("Id");

            b.HasIndex("ParentUnitId");

            b.ToTable("TodoUnits", (string)null);
          });

      modelBuilder.Entity("OrganizerBlazorApp.Domain.Entities.Attachment", b =>
          {
            b.HasOne("OrganizerBlazorApp.Domain.Entities.TodoUnit", "ParentUnit")
                      .WithMany("Attachments")
                      .HasForeignKey("ParentUnitId")
                      .OnDelete(DeleteBehavior.Cascade)
                      .IsRequired();

            b.Navigation("ParentUnit");
          });

      modelBuilder.Entity("OrganizerBlazorApp.Domain.Entities.TodoUnit", b =>
          {
            b.HasOne("OrganizerBlazorApp.Domain.Entities.TodoUnit", "ParentUnit")
                      .WithMany("SubTasks")
                      .HasForeignKey("ParentUnitId")
                      .OnDelete(DeleteBehavior.Cascade);

            b.Navigation("ParentUnit");
          });

      modelBuilder.Entity("OrganizerBlazorApp.Domain.Entities.TodoUnit", b =>
          {
            b.Navigation("Attachments");

            b.Navigation("SubTasks");
          });
#pragma warning restore 612, 618
    }
  }
}
